### ISSUE TITLE
Translation of "hacker"

### ISSUE THREAD

**Issue by wldhx** [goto-ru/paulgraham-college#13]
Straight to the point: just plain transliterating "hacker" -> "хакер" not only sounds awful, but is also semantically incorrect. Got to be a better option.

One would be "хацкер".

**Comment by danya02** [comment]
That's a bit of a problem: we don't have the idea of a hacker in Russia.

Thanks to public media, the whole world is now confused over the meaning of "hacker". In this, you are correct: an average Russian would read the word "хакер" and assume that it means "security breaker".

The initial meaning was "a person who makes furniture with an axe", and was generalized to other things that can be studied. Thus, "astronomy hacker". But it has the most flavorful meaning in computing, one that cannot be easily explained outside of context. Telling readers to go read [the English dictionary](http://catb.org/jargon/html/H/hacker.html) is just wrong.

The "хацкер" translation has the judgemental overtones that we don't want to have in our text. To wit, the word construction "кулхацкер" is more properly translated as ["script kiddie"](http://catb.org/jargon/html/S/script-kiddies.html) rather than the amplification of "hacker", ["wizard"](http://catb.org/jargon/html/W/wizard.html). The implication here is that the person in question thinks himself to be some l33t hax0r but doesn't know how the word is pronounced.

The two viable options that exist are either translating it as "программист", which is almost-but-not-quite accurate translation of the meaning we intend, or leaving it the way it is and specifying what we mean by "хакер (не взломщик)" or some similar construction.

The second option is preferable, since we do want people to appreciate the hacker culture, of which most people don't realize its existence.

**Comment by wldhx** [comment]
> The second option is preferable, since we do want people to appreciate the hacker culture, of which most people don't realize its existence.

We are talking about habr here, so I don't think this sentiment applies.

Also,

> appreciate the hacker culture

Not sure it's very close to what it's been circa 2000-s now.

> "хацкер"

Yes, I do agree that it's not a very good option (which is why I've opened the issue in the first place).

> программист

Uuh. Reminds me of "techie".

> "хакер (не взломщик)"

Ugly-ish. We could, though, put a disclaimer with `#define хакер our_honed_multiword_definition` or something at the top of the translation.

I _think_ there has to be a settled Russian equivalent; I'll ask around.

**Comment by wldhx** [comment]
> – Г-н Стаценко, как нормальные люди переводят "hacker"?
> – Хакер

**Comment by danya02** [comment]
Which implies..?

**Comment by wldhx** [comment]
I'd say that with that in mind, our best option would be using "хакер" throughout the text while including a disclaimer.

**Comment by danya02** [comment]
Seems to be the best option we have so far. The only problem we might run into is that that disclaimer might not dispel the claims, and that can be fixed if we make the disclaimer large enough to be noticed even by people who _don't_ want to notice it.

**Comment by danya02** [comment]
This is gradually becoming a stale issue. Have we decided on a solution? Will we apply one? Is it going to happen in the [copious free time](http://www.catb.org/jargon/html/C/copious-free-time.html)? Should we close the issue? Is the project production-ready? I have some more, but I think you understand the implication.

**Comment by wldhx** [comment]
@danya02 re: production-ready / what is happening

I've pinged Alexey on this.
